### ISSUE TITLE
TypeError: get_asr_dataset_from_json() got an unexpected keyword argument 'combined'

### ISSUE THREAD

**Issue by krishnanNuance** [freewym/espresso#51]
## 🐛 Bug

The following error was encountered while loading checkpoint file. 
TypeError: get_asr_dataset_from_json() got an unexpected keyword argument 'combined'

### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):
See Error:

Traceback (most recent call last):
  File "tests/test_export_asr.py", line 26, in test_jit_and_export_lstm
    'dict':'units.txt'})
  File "src/fairseq/fairseq/checkpoint_utils.py", line 273, in load_model_ensemble
    state,
  File "/src/fairseq/fairseq/checkpoint_utils.py", line 319, in load_model_ensemble_and_task
    task = tasks.setup_task(cfg.task)
  File "src/fairseq/fairseq/tasks/__init__.py", line 44, in setup_task
    return task.setup_task(cfg, **kwargs)
  File "src/fairseq/espresso/tasks/speech_recognition.py", line 271, in setup_task
    src_dataset = get_asr_dataset_from_json(data_path, cfg.gen_subset, tgt_dict, combined=False).src
TypeError: get_asr_dataset_from_json() got an unexpected keyword argument 'combined'

### Expected behavior

No syntax error

### Environment

 - fairseq Version (e.g., 1.0 or master):1.10

**Comment by freewym** [comment]
It was a typo: `combined` should be `combine`
